export { checkDependencies } from './core/binary.js';
export { probe } from './operations/probe.js';
export { convert } from './operations/convert.js';
export { trim } from './operations/trim.js';
export { extractAudio } from './operations/extract.js';
export { thumbnail } from './operations/thumbnail.js';
export { toHLS } from './operations/hls.js';
export { ffmscript, FfmScriptChain } from './operations/chain.js';
export type { SaveOptions } from './operations/chain.js';
export * from './types/index.js';
export * from './errors/index.js';
